### ISSUE TITLE
Problem with ALVideoPlayer

### ISSUE THREAD

**Issue by lukasrcp** [MagicFoundation/Alcinoe#252]
Hello.
I'm having a problem when trying to stream videos in ALVideoPlayer. These white letters appear on the screen instead of the video. I already imported all the .jar files, I already made the correction with Update.bat but I still have the same error. What to do now ?

I'm using Delphi 10.2 Sydney.

![alcinoe](https://user-images.githubusercontent.com/33559567/195099773-3d6db173-c324-4b25-abc9-4c8b9c2d49c2.jpeg)

**Comment by pcplayer** [comment]
if you apply patchs, this issue will dispear.

**Comment by Zeus64** [comment]
Hello, did the bug still present with the actual version of alcinoe that use the very last version of exoplayer jar ?

**Comment by Zeus64** [comment]
Without any answer I consider that this bug is now corrected in the very last version of Alcinoe. If not please feel free to reopen it

**Comment by lukasrcp** [comment]
I already applied all the patches and still this error persists. Some other solution.

**Comment by Zeus64** [comment]
does the same error appear in the demo https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls/_Source ?
