### ISSUE TITLE
Overschoot gone ?

### ISSUE THREAD

**Issue by Spelt** [MagicFoundation/Alcinoe#424]
'Removed Overshoot from TALInterpolatedAnimation.'

I loved that one  :-(

**Comment by Zeus64** [comment]
No, it's not a problem — it has been added back in the latest version (but not yet comited). The overshoot has now been moved into the InterpolationParams member, which also introduces new features for custom cubic Bezier interpolation. I will commit everything next week

**Comment by Spelt** [comment]
Super ! 😎 Op 27 jun 2025 om 00:29 heeft Zeus64 ***@***.***> het volgende geschreven:﻿Zeus64 left a comment (MagicFoundation/Alcinoe#424)
No, it's not a problem — it has been added back in the latest version (but not yet comited). The overshoot has now been moved into the InterpolationParams member, which also introduces new features for custom cubic Bezier interpolation. I will commit everything next week

**Comment by Elinulok32** [comment]
Hello @Zeus64,
Cannot find ADialog.GetMemo(1) supposed to be used in getting the text entered in a TALMemo added to a TALDialog. Kindly add that before you commit everything this week. Thank you.

**Comment by Zeus64** [comment]
I just committed the last version of Alcinoe with TALToggleButton

@Spelt Overshoot is now back in TALFloatAnimation 😊
@Elinulok32 No need for ADialog.GetMemo — just use ADialog.GetEdit, which returns a TALBaseEdit. Since TALMemo inherits from TALBaseEdit, you can access any memo that way.

**Comment by Spelt** [comment]
Great!😊 Op 5 jul 2025 om 02:27 heeft Zeus64 ***@***.***> het volgende geschreven:﻿Zeus64 left a comment (MagicFoundation/Alcinoe#424)
@Spelt Overshoot is now back in TALFloatAnimation 😊
@Elinulok32 No need for ADialog.GetMemo — just use ADialog.GetEdit, which returns a TALBaseEdit. Since TALMemo inherits from TALBaseEdit, you can access any memo that way.

**Comment by Elinulok32** [comment]
> No need for ADialog.GetMemo — just use ADialog.GetEdit, which returns a TALBaseEdit.

I tried that earlier on before posting the error, and I got Access violation at address ...
I just updated with your latest commit and still getting the same error. I use `.AddMemo('Handover note', '', '', 1)` to add the memo and  `use ADialog.GetEdit(1).Text;` to get the text in the Memo. I noticed that just doing "ADialog.GetEdit(1)" doesn't result in an error but doing "ADialog.GetEdit(1).Text" results in Access Violation error.

**Comment by Elinulok32** [comment]
Currently, accessing text entered in a TALMemo (added to a TALDialog) can only be achieved when you first retrieve all TALBaseEdit using "ADialog.GetEdits" and iterating through the array of TALBaseEdit. It would have been great to just use "ADialog.GetEdit(1)" like it works well with TALEdit (added to TALDialog). Anyway, great job. Still amazing.

**Comment by Zeus64** [comment]
@Elinulok32 : sorry i made a typo in the source code, you was right and i just found it and corrected it. please update your repository, now ADialog.GetEdit(1) must work

**Comment by Elinulok32** [comment]
It works now, Thank you.
